chore(readme): Update Install and Use section
Metimos/gta_vehicleDebug pull request #7
Opened 2023-06-26 00:43 UTC by Sharkiiie

2023-07-02 17:24 UTC, JajarGaming requested changes
Maybe change from Open F8 to "open chat and type `/command` or press F8 and type `command`

2023-07-02 20:04 UTC, Sharkiiie commented
Is a restricted command, it only works in F8.

2023-07-02 20:09 UTC, JajarGaming commented
Ah ok

2023-07-22 18:54 UTC, kerminal approved these changes

2023-07-22 18:55 UTC, merged